### ISSUE TITLE
 Transactions that includes the ordinary string

### ISSUE THREAD

**Issue by KORuL** [poanetwork/hydrabadger#23]
Hi! We use this repo for creating crypto-based messenger app. The are some issues and improvements suggestoins we want to introduce. It would be cool if you add the following capablities we need:

- We need to use the type of transactions that includes the ordinary string.
```
# [derive (Serialize, Deserialize, Eq, PartialEq, Hash, Ord, PartialOrd, Debug, Clone)]
pub struct Transaction (pub String);
```

**Comment by afck** [comment]
Great! Looks like this issue is resolved then. (Please reopen if I misread you.)
