### ISSUE TITLE
Error with start node

### ISSUE THREAD

**Issue by KORuL** [poanetwork/hydrabadger#8]
![47695180-d7ed2d80-dc11-11e8-8cce-2ceef1e5235e](https://user-images.githubusercontent.com/19871487/47699282-64ecb280-dc23-11e8-9248-95d664744491.png)

Start node 0..1..2  error

**Comment by c0gent** [comment]
Please try the latest changes (https://github.com/poanetwork/hydrabadger/commit/a0898ab91857b49f750d1b589f25bcc99fdecd9a) and let me know how it goes.

**Comment by KORuL** [comment]
Yes, now its work. Thank you
![screenshot from 2018-11-01 10-13-31](https://user-images.githubusercontent.com/19871487/47867488-e0cf3200-ddbe-11e8-928a-aa2743fd56e7.png)

**Comment by c0gent** [comment]
Great. Thanks again for your feedback!
